#### READING DATA FROM DIFFERENT SOURCES

In [12]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -------------------- ------------------- 2.1/4.0 MB 8.7 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.9 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [13]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in d:\programming\data_analysis\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib

   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.5.1

In [14]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, beautifulsoup4

   ------------- -------------------------- 1/3 [soupsieve]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   -------------------------- ------------- 2/3 [beautifulsoup4]
   ---------------------------------------- 3/3 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.4 typing-extensions-4.15.0

In [1]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "Suman", "email": "kundusumandeb@gmail.com", "job_profile": [{"title1": "Team Lead", "title2": "Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [2]:
df

,employee_name,email,job_profile
0,Suman,kundusumandeb@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [3]:
df.to_json()

'{"employee_name":{"0":"Suman"},"email":{"0":"kundusumandeb@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient = "index")

'{"0":{"employee_name":"Suman","email":"kundusumandeb@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:
df.to_json(orient = "records")

'[{"employee_name":"Suman","email":"kundusumandeb@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [8]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header = None)

In [10]:
df.head

<bound method NDFrame.head of      0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61

       12    13
0    3.92  1065
1    3.40  1050
2    3.17  1185
3    3.45  1480
4    2.93   735
..    ...   ...
173  1.74   740
174  1.56   750
175  1.56   835
176  1.62   840
177  1.60   560

[178 rows x 14 columns]>

In [11]:
df.to_csv("wine.csv")

In [ ]:
# url = "https://www.fdic.gov/bank/individual/failed/banklist.html"
# df = pd.read_html(url)

In [20]:
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
df = pd.read_html(url)

In [24]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [26]:
df[0].to_csv("Failed_bank_details.csv",header=0)

In [27]:
!pip install openpyxl

Requirement already satisfied: openpyxl in d:\programming\data_analysis\venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\programming\data_analysis\venv\lib\site-packages (from openpyxl) (2.0.0)

In [36]:
df_excel = pd.read_excel("name_age.xlsx")

In [37]:
df_excel.to_pickle("df_excel")

In [38]:
pd.read_pickle("df_excel")

        NAME  AGE
0      PAYEL   21
1      SUMAN   24
2  SOURYADIP   20
3     KAUSIK   21
4   NIRMALYA   21